
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (1,'Dove Shampoo','Cosmetics',5.75,500);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (2,'Dove Conditioner','Cosmetics',6.25,800);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (3,'Hefty Trash Bags','Grocery',5.99,300);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (4,'Bounty Paper Towels','Grocery',4.25,500);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (5,'Strawberries','Produce',0.35,800);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (6,'Bananas','Produce',0.20,10000);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (7,'Minute Maid Orange Juice','Grocery',4.45,250);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (8,'Danone Organic Milk','Grocery',4.50,200);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (9,'Pamper Diapers','Children',2.75,476);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (10,'Scott Toilet Paper','Grocery',12.99,700);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (11,'Pampers Baby Wipes','Children',1.50,500);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (12,'Yoga Mat','Sports',12.75,100);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (13,'Tennis Racquet','Sports',7.99,200);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (14,'Scarf','Clothing',5.55,120);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (15,'Nike T-Shirt','Clothing',17.88,250);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (16,'IAMS Dog Food','Pet',7.25,300);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (17,'Dog Joy Treats','Pet',12.50,200);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (18,'Ibuprophen','Pharmacy',4.95,500);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (19,'Band Aid','Pharmacy',3.25,550);
INSERT INTO `products` (`item_id`,`product_name`,`department_name`,`price`,`stock_quantity`) VALUES (20,'Haagen-Dazs Ice Cream','Grocery',3.25,600);
